# permissions for end users to edit hsrs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: hsr-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: kubebuilder-example
    app.kubernetes.io/part-of: kubebuilder-example
    app.kubernetes.io/managed-by: kustomize
  name: hsr-editor-role
rules:
- apiGroups:
  - deploy.example.io
  resources:
  - hsrs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - deploy.example.io
  resources:
  - hsrs/status
  verbs:
  - get
